### model
model_name_or_path: data/07_model_output/qwen/full_accu_t3/sft

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: zjob-scripts/llama_fac_config/deepspeed/ds_z3_config.json

### dataset
dataset: accu_t4
dataset_dir: zjob-scripts/llama_fac_config/data
template: qwen
cutoff_len: 9121 # 3494
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: data/07_model_output/qwen/full_accu_t4/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
# streaming: true
# max_steps: 179550
# accelerator_config:
#   dispatch_batches: false
num_train_epochs: 2.0
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
report_to: ['wandb']
resume_from_checkpoint: "data/07_model_output/qwen/full_accu_t4/sft/checkpoint-77500"

### eval
val_size: 100
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 500
save_total_limit: 1