### model
# model_name_or_path: Qwen/Qwen2-7B-Instruct
model_name_or_path: data/07_model_output/qwen/full_t0_t5/sft/previous


### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: zjob-scripts/llama_fac_config/deepspeed/ds_z3_config.json

### dataset
dataset: t0_t5
dataset_dir: zjob-scripts/llama_fac_config/data
template: qwen
cutoff_len: 20000 # 9121 # not need to know the exact number because eventually the engine only consider the actual length on the fly
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: data/07_model_output/qwen/full_t0_t5/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
# streaming: true
# max_steps: 119700
# accelerator_config:
#   dispatch_batches: false
per_device_train_batch_size: 4
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
report_to: ['wandb']
# resume_from_checkpoint: data/07_model_output/qwen/full_t0_t5/sft/checkpoint-16500

### eval
val_size: 200
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500
save_total_limit: 1